# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Test.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import FileOneToRun, os
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox


class Ui_Tester(QtWidgets.QWidget):
    def setupUi(self, Tester):
        Tester.setObjectName("Tester")
        Tester.resize(395, 350)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Cirris.jpeg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        Tester.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(Tester)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(9, 0, 181, 181))
        self.groupBox.setObjectName("groupBox")
        self.RunFileTwo = QtWidgets.QPushButton(self.groupBox)
        self.RunFileTwo.setGeometry(QtCore.QRect(20, 100, 131, 51))
        self.RunFileTwo.setObjectName("RunFileTwo")
        self.RunFileOne = QtWidgets.QPushButton(self.groupBox)
        self.RunFileOne.setGeometry(QtCore.QRect(20, 40, 131, 51))
        self.RunFileOne.setObjectName("RunFileOne")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(200, 0, 191, 80))
        self.groupBox_2.setObjectName("groupBox_2")
        self.RecordingEnco = QtWidgets.QSlider(self.groupBox_2)
        self.RecordingEnco.setGeometry(QtCore.QRect(10, 30, 160, 16))
        self.RecordingEnco.setOrientation(QtCore.Qt.Horizontal)
        self.RecordingEnco.setObjectName("RecordingEnco")
        self.checkBox = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox.setGeometry(QtCore.QRect(10, 50, 92, 23))
        self.checkBox.setObjectName("checkBox")
        self.CloseButton = QtWidgets.QPushButton(self.centralwidget)
        self.CloseButton.setGeometry(QtCore.QRect(300, 280, 89, 25))
        self.CloseButton.setObjectName("CloseButton")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 190, 181, 121))
        self.groupBox_3.setObjectName("groupBox_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_4.setGeometry(QtCore.QRect(10, 30, 89, 25))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_5.setGeometry(QtCore.QRect(10, 70, 89, 25))
        self.pushButton_5.setObjectName("pushButton_5")
        self.groupBox_2.raise_()
        self.groupBox.raise_()
        self.CloseButton.raise_()
        self.groupBox_3.raise_()
        Tester.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Tester)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 395, 22))
        self.menubar.setObjectName("menubar")
        Tester.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Tester)
        self.statusbar.setObjectName("statusbar")
        Tester.setStatusBar(self.statusbar)

        self.retranslateUi(Tester)
        QtCore.QMetaObject.connectSlotsByName(Tester)
        self.CloseButton.clicked.connect(self.closeEvent)
        self.RunFileOne.clicked.connect(self.runFileOneEvent)
        self.RunFileTwo.clicked.connect(self.runFileTwoEvent)
    def closeEvent(self, event):
        reply = QMessageBox.question(self,"QUIT","Sure?",QMessageBox.Yes | QMessageBox.No)
        if reply == QMessageBox.Yes:
            if not type(event) == bool:
                event.accept()
            else:
                sys.exit()
        else:
            if not type(event) == bool:
                event.ignore()
    def runFileOneEvent(self):
        os.system('python FileOneToRun.py')

    def runFileTwoEvent(self):
        NewValue=FileOneToRun.GetValue()
        print(NewValue)

    def retranslateUi(self, Tester):
        _translate = QtCore.QCoreApplication.translate
        Tester.setWindowTitle(_translate("Tester", "TestGuiWill"))
        self.groupBox.setTitle(_translate("Tester", "Files"))
        self.RunFileTwo.setText(_translate("Tester", "Run File 2"))
        self.RunFileOne.setText(_translate("Tester", "Run File 1"))
        self.groupBox_2.setTitle(_translate("Tester", "Encoder"))
        self.checkBox.setText(_translate("Tester", "Recording"))
        self.CloseButton.setText(_translate("Tester", "Close"))
        self.groupBox_3.setTitle(_translate("Tester", "Display Data"))
        self.pushButton_4.setText(_translate("Tester", "PushButton"))
        self.pushButton_5.setText(_translate("Tester", "PushButton"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Tester = QtWidgets.QMainWindow()
    ui = Ui_Tester()
    ui.setupUi(Tester)
    Tester.show()
    sys.exit(app.exec_())
