# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Test.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
# -------------------------------------------------------------------------
# This code has been developped by: William Bonilla
# For any questions you can contact my at miloubonilla@gmail.com
# -------------------------------------------------------------------------
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
from PyQt5.QtWidgets import *
from
import sys
sys.path.insert(1,'/home/william/Documents/Cirris/Git_Repo/api_phidget_n_MQTT/src/')
import phidget22PlotLastLogMeasures.py

class Ui_Tester(QWidget):
    def setupUi(self, Tester):
        Tester.setObjectName("Tester")
        Tester.resize(673, 461)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../Downloads/Cirris.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Tester.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(Tester)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(9, 0, 181, 161))
        self.groupBox.setObjectName("groupBox")
        self.RunFileTwo = QtWidgets.QPushButton(self.groupBox)
        self.RunFileTwo.setGeometry(QtCore.QRect(20, 100, 131, 51))
        self.RunFileTwo.setObjectName("RunFileTwo")
        self.RunFileOne = QtWidgets.QPushButton(self.groupBox)
        self.RunFileOne.setGeometry(QtCore.QRect(20, 40, 131, 51))
        self.RunFileOne.setObjectName("RunFileOne")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(200, 0, 191, 80))
        self.groupBox_2.setObjectName("groupBox_2")
        self.EncoOnOffB = QtWidgets.QSlider(self.groupBox_2)
        self.EncoOnOffB.setGeometry(QtCore.QRect(10, 30, 160, 16))
        self.EncoOnOffB.setOrientation(QtCore.Qt.Horizontal)
        self.EncoOnOffB.setObjectName("EncoOnOffB")
        self.RegisterEnco = QtWidgets.QCheckBox(self.groupBox_2)
        self.RegisterEnco.setGeometry(QtCore.QRect(10, 50, 141, 23))
        self.RegisterEnco.setObjectName("RegisterEnco")
        self.CloseButton = QtWidgets.QPushButton(self.centralwidget)
        self.CloseButton.setGeometry(QtCore.QRect(580, 390, 89, 25))
        self.CloseButton.setObjectName("CloseButton")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 170, 181, 171))
        self.groupBox_3.setObjectName("groupBox_3")
        self.DisplayPlotButton = QtWidgets.QPushButton(self.groupBox_3)
        self.DisplayPlotButton.setGeometry(QtCore.QRect(10, 140, 161, 25))
        self.DisplayPlotButton.setObjectName("DisplayPlotButton")
        self.lcdNumber = QtWidgets.QLCDNumber(self.groupBox_3)
        self.lcdNumber.setGeometry(QtCore.QRect(10, 30, 141, 51))
        self.lcdNumber.setObjectName("lcdNumber")
        self.label_3 = QtWidgets.QLabel(self.groupBox_3)
        self.label_3.setGeometry(QtCore.QRect(10, 80, 161, 17))
        self.label_3.setObjectName("label_3")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(400, 0, 271, 341))
        self.groupBox_4.setObjectName("groupBox_4")
        self.textEditFile = QtWidgets.QTextEdit(self.groupBox_4)
        self.textEditFile.setGeometry(QtCore.QRect(10, 50, 251, 70))
        self.textEditFile.setObjectName("textEditFile")
        self.FIleLabel = QtWidgets.QLabel(self.groupBox_4)
        self.FIleLabel.setGeometry(QtCore.QRect(10, 30, 67, 17))
        self.FIleLabel.setObjectName("FIleLabel")
        self.FileConfirmButton = QtWidgets.QPushButton(self.groupBox_4)
        self.FileConfirmButton.setGeometry(QtCore.QRect(10, 130, 251, 25))
        self.FileConfirmButton.setObjectName("FileConfirmButton")
        self.textEditDirectory = QtWidgets.QTextEdit(self.groupBox_4)
        self.textEditDirectory.setGeometry(QtCore.QRect(10, 200, 251, 70))
        self.textEditDirectory.setObjectName("textEditDirectory")
        self.DirectoryConfirmB = QtWidgets.QPushButton(self.groupBox_4)
        self.DirectoryConfirmB.setGeometry(QtCore.QRect(10, 280, 251, 25))
        self.DirectoryConfirmB.setObjectName("DirectoryConfirmB")
        self.DirectorLabel = QtWidgets.QLabel(self.groupBox_4)
        self.DirectorLabel.setGeometry(QtCore.QRect(10, 180, 67, 17))
        self.DirectorLabel.setObjectName("DirectorLabel")
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_5.setGeometry(QtCore.QRect(200, 100, 191, 111))
        self.groupBox_5.setObjectName("groupBox_5")
        self.ToConnectButton = QtWidgets.QPushButton(self.groupBox_5)
        self.ToConnectButton.setGeometry(QtCore.QRect(10, 30, 171, 31))
        self.ToConnectButton.setObjectName("ToConnectButton")
        self.ToDisconnectButton = QtWidgets.QPushButton(self.groupBox_5)
        self.ToDisconnectButton.setGeometry(QtCore.QRect(10, 70, 171, 31))
        self.ToDisconnectButton.setObjectName("ToDisconnectButton")
        self.groupBox_2.raise_()
        self.groupBox.raise_()
        self.CloseButton.raise_()
        self.groupBox_3.raise_()
        self.groupBox_4.raise_()
        self.groupBox_5.raise_()
        Tester.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Tester)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 673, 22))
        self.menubar.setObjectName("menubar")
        Tester.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Tester)
        self.statusbar.setObjectName("statusbar")
        Tester.setStatusBar(self.statusbar)
        self.retranslateUi(Tester)
        self.centerOnScreen()
        QtCore.QMetaObject.connectSlotsByName(Tester)
        # User interaction---------------------------------------------------------------------------------------------------------------------------------------
        self.CloseButton.clicked.connect(self.closeEvent)
        self.RegisterEnco.stateChanged.connect(self.registerIsOnMessage)
        self.DisplayPlotButton.clicked.connect(self.PlotData)



    def centerOnScreen(self):
        qtRectangle = self.frameGeometry()
        centerPoint = QDesktopWidget().availableGeometry().center()
        qtRectangle.moveCenter(centerPoint)
        self.move(qtRectangle.topLeft())

    # All coded actions
    # Functions--------------------------------------------------------------------------------------------------------------------------------------------
    def closeEvent(self, event):
        reply = QMessageBox.question(self, 'Quit?', 'Are you sure you want to quit?', QMessageBox.Yes | QMessageBox.No,QMessageBox.No)
        if reply == QMessageBox.Yes:
            if not type(event) == bool:
                event.accept()
            else:
                sys.exit()
        else:
            if not type(event) == bool:
                event.ignore()
    def registerIsOnMessage(self, int):
        if self.RegisterEnco.isChecked():
            recordIsOn = QMessageBox()
            recordIsOn.setIcon(QMessageBox.Information)
            recordIsOn.setText("Recording has started")
            recordIsOn.setWindowTitle("Information recording")
            recordIsOn.setStandardButtons(QMessageBox.Ok)
            recordIsOn.exec_()
        else:
            recordIsOff = QMessageBox()
            recordIsOff.setIcon(QMessageBox.Information)
            recordIsOff.setText("Recording is done")
            recordIsOff.setWindowTitle("Information recording")
            recordIsOff.setStandardButtons(QMessageBox.Ok)
            recordIsOff.exec_()
    def PlotData(self):
        print("Hello World")

    def retranslateUi(self, Tester):
        _translate = QtCore.QCoreApplication.translate
        Tester.setWindowTitle(_translate("Tester", "Interface de contrôle"))
        self.groupBox.setTitle(_translate("Tester", "Fichier"))
        self.RunFileTwo.setText(_translate("Tester", "Phidget"))
        self.RunFileOne.setText(_translate("Tester", "Gaspar"))
        self.groupBox_2.setTitle(_translate("Tester", "Encodeur"))
        self.RegisterEnco.setText(_translate("Tester", "Enregistrement"))
        self.CloseButton.setText(_translate("Tester", "Fermer"))
        self.groupBox_3.setTitle(_translate("Tester", "Afficher données"))
        self.DisplayPlotButton.setText(_translate("Tester", "Graphique de donnée"))
        self.label_3.setText(_translate("Tester", "Valeur en temps réel"))
        self.groupBox_4.setTitle(_translate("Tester", "Fichier"))
        self.FIleLabel.setText(_translate("Tester", "Fichier"))
        self.FileConfirmButton.setText(_translate("Tester", "Confirmer"))
        self.DirectoryConfirmB.setText(_translate("Tester", "Confirmer"))
        self.DirectorLabel.setText(_translate("Tester", "Dossier"))
        self.groupBox_5.setTitle(_translate("Tester", "Connectivité"))
        self.ToConnectButton.setText(_translate("Tester", "Lancer connexion"))
        self.ToDisconnectButton.setText(_translate("Tester", "Déconnexion"))


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    Tester = QtWidgets.QMainWindow()
    ui = Ui_Tester()
    ui.setupUi(Tester)
    Tester.show()
    sys.exit(app.exec_())
